import {TChatListItem} from '../Types/ChatList.types';
import {TUser} from '../Types/Message.types';
const loggedInUser: TUser = {_id: 1, name: 'Kevin'};

const list: TChatListItem[] = [
  {
    _id: 2,
    name: 'Tommy',
    avatar: 'https://picsum.photos/200/300',
    lastMessage: {
      _id: 23,
      type: 'audio',
      audio:
        'https://file-examples.com/storage/fe15076da466528199d9c5a/2017/11/file_example_MP3_2MG.mp3',
      createdAt: new Date(),
      sender: loggedInUser,
      receiver: {
        _id: 2,
        name: 'Tommy',
        avatar: 'https://picsum.photos/200/300',
      },
      status: 'read',
    },
    noOfUnreadMessages: 0,
    isMuted: true,
    isPinned: false,
    isSelected: false,
    isArchived: false,
    isMarkedAsUnread: true,
    type: 'Individual',
  },
  {
    _id: 3,
    name: 'Naveen',
    avatar: 'https://picsum.photos/200/300',
    lastMessage: {
      _id: 5,
      type: 'location',
      location: {
        latitude: 34.04319082995527,
        longitude: -118.26677130605509,
      },
      createdAt: new Date(),
      status: 'read',
      sender: {
        _id: 3,
        name: 'Naveen',
        avatar: 'https://picsum.photos/200/300',
      },
      receiver: loggedInUser,
    },
    noOfUnreadMessages: 2,
    isMuted: false,
    isPinned: false,
    isSelected: false,
    isArchived: false,
    isMarkedAsUnread: false,
    type: 'Individual',
  },
  {
    _id: 4,
    name: 'Mahesh',
    avatar: 'https://picsum.photos/200/300',
    lastMessage: {
      _id: 22,
      type: 'text',
      text: 'Hi',
      createdAt: new Date(),
      status: 'read',
      sender: {
        _id: 4,
        name: 'Mahesh',
        avatar: 'https://picsum.photos/200/300',
      },
      receiver: loggedInUser,
    },
    noOfUnreadMessages: 18,
    isMuted: false,
    isPinned: false,
    isSelected: false,
    isArchived: false,
    isMarkedAsUnread: false,
    type: 'Individual',
  },
  {
    _id: 5,
    name: 'David',
    avatar: 'https://picsum.photos/200/300',
    lastMessage: {
      _id: 22,
      type: 'text',
      text: 'This is a Video type message',
      createdAt: new Date('2024-06-02T04:48:11.677Z'),
      status: 'delivered',
      sender: loggedInUser,
      receiver: {
        _id: 5,
        name: 'David',
        avatar: 'https://picsum.photos/200/300',
      },
    },
    noOfUnreadMessages: 0,
    isMuted: false,
    isPinned: false,
    isSelected: false,
    isArchived: false,
    isMarkedAsUnread: false,
    type: 'Individual',
  },
  {
    _id: 6,
    name: 'Ryan',
    avatar: 'https://picsum.photos/200/300',
    lastMessage: {
      _id: 22,
      type: 'text',
      text: 'This is a Video type message',
      createdAt: new Date('2024-06-03T04:48:11.677Z'),
      status: 'read',
      sender: loggedInUser,
      receiver: {
        _id: 6,
        name: 'Ryan',
        avatar: 'https://picsum.photos/200/300',
      },
    },
    noOfUnreadMessages: 1,
    isMuted: false,
    isPinned: false,
    isSelected: false,
    isArchived: false,
    isMarkedAsUnread: false,
    type: 'Individual',
  },
  {
    _id: 7,
    name: 'John Doe',
    avatar: 'https://picsum.photos/200/300',
    lastMessage: {
      _id: 23,
      type: 'audio',
      audio:
        'https://file-examples.com/storage/fe15076da466528199d9c5a/2017/11/file_example_MP3_2MG.mp3',
      createdAt: new Date(),
      sender: loggedInUser,
      receiver: {
        _id: 2,
        name: 'Tommy',
        avatar: 'https://picsum.photos/200/300',
      },
      status: 'read',
    },
    noOfUnreadMessages: 0,
    isMuted: false,
    isPinned: false,
    isSelected: false,
    isArchived: false,
    isMarkedAsUnread: false,
    type: 'Individual',
  },
  {
    _id: 8,
    name: 'Jane Smith',
    avatar: 'https://picsum.photos/200/300',
    lastMessage: {
      _id: 5,
      type: 'location',
      location: {
        latitude: 34.04319082995527,
        longitude: -118.26677130605509,
      },
      createdAt: new Date(),
      status: 'read',
      sender: {
        _id: 3,
        name: 'Naveen',
        avatar: 'https://picsum.photos/200/300',
      },
      receiver: loggedInUser,
    },
    noOfUnreadMessages: 2,
    isMuted: false,
    isPinned: false,
    isSelected: false,
    isArchived: false,
    isMarkedAsUnread: false,
    type: 'Individual',
  },
  {
    _id: 9,
    name: 'Emily Davis',
    avatar: 'https://picsum.photos/200/300',
    lastMessage: {
      _id: 22,
      type: 'text',
      text: 'Hi',
      createdAt: new Date(),
      status: 'read',
      sender: {
        _id: 4,
        name: 'Mahesh',
        avatar: 'https://picsum.photos/200/300',
      },
      receiver: loggedInUser,
    },
    noOfUnreadMessages: 18,
    isMuted: false,
    isPinned: false,
    isSelected: false,
    isArchived: false,
    isMarkedAsUnread: false,
    type: 'Group',
  },
  {
    _id: 10,
    name: 'Christopher Brown',
    avatar: 'https://picsum.photos/200/300',
    lastMessage: {
      _id: 22,
      type: 'text',
      text: 'This is a Video type message',
      createdAt: new Date('2024-06-02T04:48:11.677Z'),
      status: 'delivered',
      sender: loggedInUser,
      receiver: {
        _id: 5,
        name: 'David',
        avatar: 'https://picsum.photos/200/300',
      },
    },
    noOfUnreadMessages: 0,
    isMuted: false,
    isPinned: false,
    isSelected: false,
    isArchived: false,
    isMarkedAsUnread: false,
    type: 'Individual',
  },
  {
    _id: 11,
    name: 'Joshua Wilson',
    avatar: 'https://picsum.photos/200/300',
    lastMessage: {
      _id: 22,
      type: 'text',
      text: 'This is a Video type message',
      createdAt: new Date('2024-06-03T04:48:11.677Z'),
      status: 'read',
      sender: loggedInUser,
      receiver: {
        _id: 6,
        name: 'Ryan',
        avatar: 'https://picsum.photos/200/300',
      },
    },
    noOfUnreadMessages: 1,
    isMuted: false,
    isPinned: false,
    isSelected: false,
    isArchived: false,
    isMarkedAsUnread: false,
    type: 'Individual',
  },
  {
    _id: 12,
    name: 'Sarah Lee',
    avatar: 'https://picsum.photos/200/300',
    lastMessage: {
      _id: 23,
      type: 'audio',
      audio:
        'https://file-examples.com/storage/fe15076da466528199d9c5a/2017/11/file_example_MP3_2MG.mp3',
      createdAt: new Date(),
      sender: loggedInUser,
      receiver: {
        _id: 2,
        name: 'Tommy',
        avatar: 'https://picsum.photos/200/300',
      },
      status: 'read',
    },
    noOfUnreadMessages: 0,
    isMuted: false,
    isPinned: false,
    isSelected: false,
    isArchived: false,
    isMarkedAsUnread: false,
    type: 'Individual',
  },
  {
    _id: 13,
    name: 'David Taylor',
    avatar: 'https://picsum.photos/200/300',
    lastMessage: {
      _id: 5,
      type: 'location',
      location: {
        latitude: 34.04319082995527,
        longitude: -118.26677130605509,
      },
      createdAt: new Date(),
      status: 'read',
      sender: {
        _id: 3,
        name: 'Naveen',
        avatar: 'https://picsum.photos/200/300',
      },
      receiver: loggedInUser,
    },
    noOfUnreadMessages: 2,
    isMuted: false,
    isPinned: false,
    isSelected: false,
    isArchived: false,
    isMarkedAsUnread: false,
    type: 'Individual',
  },
  {
    _id: 14,
    name: 'Olivia Anderson',
    avatar: 'https://picsum.photos/200/300',
    lastMessage: {
      _id: 22,
      type: 'text',
      text: 'Hi',
      createdAt: new Date('2024-06-01T04:48:11.677Z'),
      status: 'read',
      sender: {
        _id: 4,
        name: 'Mahesh',
        avatar: 'https://picsum.photos/200/300',
      },
      receiver: loggedInUser,
    },
    noOfUnreadMessages: 18,
    isMuted: false,
    isPinned: false,
    isSelected: false,
    isArchived: false,
    isMarkedAsUnread: false,
    type: 'Individual',
  },
  {
    _id: 15,
    name: 'Daniel Thomas',
    avatar: 'https://picsum.photos/200/300',
    lastMessage: {
      _id: 22,
      type: 'text',
      text: 'This is a Video type message',
      createdAt: new Date('2024-06-02T04:48:11.677Z'),
      status: 'delivered',
      sender: loggedInUser,
      receiver: {
        _id: 5,
        name: 'David',
        avatar: 'https://picsum.photos/200/300',
      },
    },
    noOfUnreadMessages: 0,
    isMuted: false,
    isPinned: false,
    isSelected: false,
    isArchived: false,
    isMarkedAsUnread: false,
    type: 'Group',
  },
  {
    _id: 16,
    name: 'Laura Harris',
    avatar: 'https://picsum.photos/200/300',
    lastMessage: {
      _id: 22,
      type: 'text',
      text: 'This is a Video type message',
      createdAt: new Date('2024-06-03T04:48:11.677Z'),
      status: 'read',
      sender: loggedInUser,
      receiver: {
        _id: 6,
        name: 'Ryan',
        avatar: 'https://picsum.photos/200/300',
      },
    },
    noOfUnreadMessages: 1,
    isMuted: false,
    isPinned: false,
    isSelected: false,
    isArchived: false,
    isMarkedAsUnread: false,
    type: 'Individual',
  },
];
export default list;
