name: react-native-test

on:
  pull_request:
    types: [opened, edited]
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Install npm dependencies
      - name: Install npm dependencies
        run: |
          npm install --force

      - name: Run tests
        run: |
          npm run test -- -u
